/***************CREATE DATABASE*********************/
CREATE DATABASE LIBRARY_DB

GO

/*****************************************************/

USE LIBRARY_DB

/***************************** USERS ********************************/
CREATE TABLE [dbo].[USERS]
(
	 ID INT IDENTITY(1,1) NOT NULL,
	 NAME VARCHAR(100) NOT NULL,
	 EMAIL VARCHAR(100) NOT NULL,
	 CONSTRAINT [PK_USERS] PRIMARY KEY CLUSTERED
(ID ASC) ON [PRIMARY])
GO

/***************************** BOOKS ********************************/
CREATE TABLE [dbo].[BOOKS]
(
	 ID INT IDENTITY(1,1) NOT NULL,
	 NAME VARCHAR(100) NOT NULL,
	 AUTHOR VARCHAR(100) NOT NULL,
	 IS_AVAILABLE BIT,
	 ISBN VARCHAR(100) NOT NULL,
	 CONSTRAINT [PK_BOOKS] PRIMARY KEY CLUSTERED
(ID ASC) ON [PRIMARY])
GO


/***************************** BORROWINGS ********************************/
CREATE TABLE [dbo].[BORROWINGS]
(
	 ID INT IDENTITY(1,1) NOT NULL,
	 USER_ID INT NOT NULL,
	 BOOK_ID INT NOT NULL,
	 CONSTRAINT [PK_BORROWINGS] PRIMARY KEY CLUSTERED
(ID ASC) ON [PRIMARY])
GO

ALTER TABLE [dbo].[BORROWINGS]  WITH CHECK ADD  CONSTRAINT [FK_USERS] FOREIGN KEY([USER_ID])
REFERENCES [dbo].[USERS] ([ID])
GO

ALTER TABLE [dbo].[BORROWINGS]  WITH CHECK ADD  CONSTRAINT [FK_BOOKS] FOREIGN KEY([BOOK_ID])
REFERENCES [dbo].[BOOKS] ([ID])
GO

